defaults: ../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 2
  num_generations_per_prompt: 8
  max_num_steps: 500
checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-nanov3-30BA3B-4n4g-megatron_colocated_reshard
  save_period: 100
policy:
  model_name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-Base-BF16
  tokenizer:
    name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
  train_global_batch_size: 16
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 2048
  megatron_cfg:
    enabled: true
    bias_activation_fusion: false
    tensor_model_parallel_size: 2
    expert_model_parallel_size: 8
    sequence_parallel: true
  dtensor_cfg:
    enabled: false
  sequence_packing:
    enabled: false
  generation:
    backend: megatron
    mcore_generation_config:
      transformer_impl: inference_optimized
      moe_router_dtype: fp32
      activation_checkpointing: false
      tensor_model_parallel_size: 4
      expert_model_parallel_size: 4
      sequence_parallel: true
logger:
  log_dir: logs/grpo-nanov3-30BA3B-4n4g-megatron_colocated_reshard
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-nanov3-30BA3B-4n4g-megatron_colocated_reshard
cluster:
  gpus_per_node: 4
  num_nodes: 4
  segment_size: 2
