defaults: ../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 2
  num_generations_per_prompt: 8
checkpointing:
  checkpoint_dir: results/grpo-nanov3-30BA3B-2n8g-megatron_generation
policy:
  model_name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-Base-BF16
  tokenizer:
    name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
  train_global_batch_size: 16
  train_micro_batch_size: 1
  logprob_batch_size: 1
  max_total_sequence_length: 2048
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    bias_activation_fusion: false
    tensor_model_parallel_size: 2
    expert_model_parallel_size: 8
    sequence_parallel: true
    moe_router_dtype: fp32
  sequence_packing:
    enabled: false
  generation:
    backend: megatron
    mcore_generation_config:
      transformer_impl: inference_optimized
      inference_grouped_gemm_backend: "vllm"
      moe_router_num_groups: null
      moe_router_group_topk: null
      activation_checkpointing: false
      tensor_model_parallel_size: 2
      expert_model_parallel_size: 8
      sequence_parallel: true
    colocated:
      enabled: false
      resources:
        gpus_per_node: 8
        num_nodes: 1
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-nanov3-30BA3B-2n8g-megatron_generation
cluster:
  gpus_per_node: 8
  num_nodes: 2
