defaults: ../../../nemo_gym/grpo_nanov3.yaml
grpo:
  async_grpo:
    enabled: true
    in_flight_weight_updates: true
  overlong_filtering: false
checkpointing:
  checkpoint_dir: results/grpo-nanov3-30BA3B-2n8g-megatron_generation-async-gym
policy:
  model_name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-Base-BF16
  tokenizer:
    name: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
  train_global_batch_size: 16
  max_total_sequence_length: 2048
  megatron_cfg:
    pipeline_model_parallel_size: 1
    context_parallel_size: 2
  generation:
    backend: megatron
    colocated:
      enabled: false
      resources:
        gpus_per_node: 8
        num_nodes: 1
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-nanov3-30BA3B-2n8g-megatron_generation-async-gym
cluster:
  num_nodes: 2
