defaults: ./grpo-qwen2.5-math-1.5b-instruct-1n8g-megatron-single-controller-sync.yaml

logger:
  log_dir: logs/grpo-qwen2.5-math-1.5b-instruct-1n4g-megatron-single-controller-sync
  wandb:
    name: grpo-qwen2.5-math-1.5b-instruct-1n4g-megatron-single-controller-sync

checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-math-1.5b-instruct-1n4g-megatron-single-controller-sync

policy:
  generation:
    colocated:
      resources:
        gpus_per_node: 2

cluster:
  gpus_per_node: 4
