# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Approve Test Queue

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  approve-test-queue:
    if: github.repository == 'NVIDIA-NeMo/RL'
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_test_approval_queue.yml@7a39dff97817b673465972a0e1a1c3c9dbc25372 # v1.3.0
    with:
      workflow_name: CICD NeMo RL
      max_concurrency_internal: ${{ fromJSON(vars.MAX_CONCURRENCY || '3') }}
      max_concurrency_external: ${{ fromJSON(vars.MAX_CONCURRENCY_EXTERNAL || '3') }}
    secrets:
      PAT: ${{ secrets.PAT }}
      NVIDIA_MANAGEMENT_ORG_PAT: ${{ secrets.NVIDIA_MANAGEMENT_ORG_PAT }}
      SLACK_CI_CHANNEL_WEBHOOK: ${{ secrets.SLACK_GITHUB_CI_WEBHOOK }}
      SLACK_TEAM_GROUP_ID: ${{ secrets.SLACK_TEAM_GROUP_ID }}
